---

- name: Login with admin user
  uri:
    url: "http://{{ ansible_host }}:{{ archiva.port }}/{{ archiva.loginEndpoint }}"
    method: POST
    body: '{{ { "username": "admin", "password": archiva_admin.password } | to_json }}'
    HEADER_Content-Type: "application/json"
  register: login

- name: Create users
  uri:
    url: "http://{{ ansible_host }}:{{ archiva.port }}/{{ archiva.createUserEndpoint }}"
    method: POST
    return_content: yes
    HEADER_Cookie: "{{ login.set_cookie }}"
    HEADER_Content-Type: "application/json"
    body_format: json
    body: "{{ item | combine({'confirmPassword': item.password}) | to_json }}"
  with_items: "{{ archiva_users }}"
