---

- name: Login with admin user
  uri:
    url: "{{ archiva.protocol }}://{{ ansible_host }}:{{ archiva.port }}/{{ archiva.loginEndpoint }}"
    method: POST
    body: '{{ { "username": "admin", "password": archiva_admin.password } | to_json }}'
    HEADER_Content-Type: "application/json"
  register: login

- name: Create repositories
  uri:
    url: "{{ archiva.protocol }}://{{ ansible_host }}:{{ archiva.port }}/{{ archiva.createManagedRepositoryEndpoint }}"
    method: POST
    return_content: yes
    HEADER_Cookie: "{{ login.set_cookie }}"
    HEADER_Content-Type: "application/json"
    body: "{{ item | to_json }}"
  with_items: "{{ archiva_repositories }}"
