---
# tasks file for ansible-role-archiva

- name: Install Apache Archiva {{ archiva_version }}
  include: install.yml
  tags:
    - archiva
    - install
  when: not onlyconfig 

- name: Create Archiva admin automatically
  include: create-admin.yml
  tags:
    - archiva
    - configure
  when: archiva_admin_password is defined and archiva_admin_email is defined

- name: Create Archiva users
  include: create-users.yml
  tags:
    - archiva
    - configure
  when: archiva_admin_password is defined and archiva_users is defined
