---
# tasks file for ansible-role-archiva

- name: Install Apache Archiva {{ archiva_version }}
  include: install.yml
  tags:
    - archiva
    - install
  when: configonly is not defined or not configonly

- name: Create Archiva admin automatically
  include: create-admin.yml
  tags:
    - archiva
    - configure
  when: archiva_admin is defined

- name: Create Archiva users
  include: create-users.yml
  tags:
    - archiva
    - configure
  when: archiva_admin is defined and archiva_users is defined
